export const RECEIVE_TWEETS = 'RECEIVE_TWEETS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const ADD_TWEET = "ADD_TWEET"
export const TOGGLE_TWEET = "TOGGLE_TWEET"
export const SET_AUTHED_USER = "SET_AUTHED_USER"